# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recipes-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TagListView', '~> 1.0'
  pod 'Google-Mobile-Ads-SDK'  
  pod 'HGCircularSlider'
  pod 'IQKeyboardManagerSwift'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

  # Pods for Recipes-App

  target 'Recipes-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
